<a href="https://colab.research.google.com/github/Macostik/ML_course/blob/main/home_work_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import numpy as np

In [64]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Mounted at /content/drive

Get Iris list dataSet

In [83]:
# Getting Iris dataset (first four columns without target)
iris_dataset = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype=float, delimiter=',', usecols=(0,1,2,3))

Get info about Iris dataSet

In [66]:
print("Shape of array: ", iris_dataset.shape)
print("Type of array: ", type(iris_dataset))
print("Look first twenty items:\n", iris_dataset[:20])

Shape of array:  (150, 4)
Type of array:  <class 'numpy.ndarray'>
Look first twenty items:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]]


Count mean, median, standard deviation for first row

In [67]:
# Calculate mean value
mean_value = np.mean(iris_dataset, axis=1)
print("Mean value: \n", mean_value)

Mean value: 
 [2.55  2.375 2.35  2.35  2.55  2.85  2.425 2.525 2.225 2.4   2.7   2.5
 2.325 2.125 2.8   3.    2.75  2.575 2.875 2.675 2.675 2.675 2.35  2.65
 2.575 2.45  2.6   2.6   2.55  2.425 2.425 2.675 2.725 2.825 2.4   2.4
 2.625 2.4   2.225 2.55  2.525 2.1   2.275 2.675 2.8   2.375 2.675 2.35
 2.675 2.475 4.075 3.9   4.1   3.275 3.85  3.575 3.975 2.9   3.85  3.3
 2.875 3.65  3.3   3.775 3.35  3.9   3.65  3.4   3.6   3.275 3.925 3.55
 3.8   3.7   3.725 3.85  3.95  4.1   3.725 3.2   3.2   3.15  3.4   3.85
 3.6   3.875 4.    3.575 3.5   3.325 3.425 3.775 3.4   2.9   3.45  3.525
 3.525 3.675 2.925 3.475 4.525 3.875 4.525 4.15  4.375 4.825 3.4   4.575
 4.2   4.85  4.2   4.075 4.35  3.8   4.025 4.3   4.2   5.1   4.875 3.675
 4.525 3.825 4.8   3.925 4.45  4.55  3.9   3.95  4.225 4.4   4.55  5.025
 4.25  3.925 3.925 4.775 4.425 4.2   3.9   4.375 4.45  4.35  3.875 4.55
 4.55  4.3   3.925 4.175 4.325 3.95 ]


In [68]:
# Calculate median value
median_value = np.median(iris_dataset, axis=1)
print("Median value: \n", median_value)

Median value: 
 [2.45 2.2  2.25 2.3  2.5  2.8  2.4  2.45 2.15 2.3  2.6  2.5  2.2  2.05
 2.6  2.95 2.6  2.45 2.75 2.65 2.55 2.6  2.3  2.5  2.65 2.3  2.5  2.5
 2.4  2.4  2.35 2.45 2.8  2.8  2.3  2.2  2.4  2.3  2.15 2.45 2.4  1.8
 2.25 2.55 2.85 2.2  2.7  2.3  2.6  2.35 3.95 3.85 4.   3.15 3.7  3.65
 4.   2.85 3.75 3.3  2.75 3.6  3.1  3.8  3.25 3.75 3.75 3.4  3.35 3.2
 4.   3.4  3.7  3.75 3.6  3.7  3.8  4.   3.7  3.05 3.1  3.05 3.3  3.9
 3.75 3.95 3.9  3.35 3.55 3.25 3.5  3.8  3.3  2.8  3.45 3.6  3.55 3.6
 2.75 3.45 4.65 3.9  4.45 4.25 4.4  4.8  3.5  4.6  4.15 4.85 4.15 4.
 4.25 3.75 3.95 4.25 4.25 5.25 4.75 3.6  4.45 3.85 4.75 3.8  4.5  4.6
 3.8  3.95 4.2  4.4  4.45 5.1  4.2  3.95 4.1  4.55 4.5  4.3  3.9  4.25
 4.35 4.1  3.9  4.55 4.5  4.1  3.75 4.1  4.4  4.05]


In [69]:
# Calculate standard deviation value
std_value = np.std(iris_dataset, axis=1)
print("Standard deviation value: \n", std_value)

Standard deviation value: 
 [1.88745861 1.76405074 1.72988439 1.65604952 1.86748494 1.93196791
 1.67686463 1.82671153 1.57856739 1.79164729 1.99874961 1.74642492
 1.75979402 1.63152536 2.22261108 2.13658606 1.99812412 1.85657615
 2.05228531 1.88198698 1.93826598 1.83626659 1.80762275 1.7284386
 1.71227188 1.7741195  1.74928557 1.9065676  1.90984293 1.68874954
 1.71227188 1.90443561 2.02530862 2.1194044  1.79164729 1.8493242
 2.04129248 1.79164729 1.60370664 1.86077941 1.83898749 1.55563492
 1.62999233 1.69908063 1.79304211 1.69760861 1.89917745 1.68151717
 1.96516539 1.82944664 2.0535031  1.79304211 2.01494417 1.6068214
 1.88480768 1.6693936  1.73403431 1.41598023 1.97040605 1.40890028
 1.51554446 1.61322658 1.88944436 1.77957158 1.5435349  1.93520025
 1.54677083 1.76776695 1.86681547 1.66789538 1.55784306 1.75570499
 1.9        1.85876303 1.87399973 1.90984293 2.04144557 1.9065676
 1.68874954 1.69852878 1.63554272 1.659066   1.68374582 1.77270979
 1.48492424 1.60526478 1.92613603 1.93

Set 20 NaN values to a random unique position in Iris dataset

In [70]:
# Choose random unique index from Iris dataset
idx = np.random.choice(iris_dataset.size, 20, replace=False)
# Replace value with NaN by index
iris_dataset.flat[idx] = np.nan
print("Look first twenty items:\n", iris_dataset[:20])

Look first twenty items:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 nan 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 nan 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 nan]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 nan nan 0.3]]


Check unique postions

In [71]:
# Get a unique index and counts
unique_indexes, counts = np.unique(idx, return_counts=True)
print("Unique indexes : ", unique_indexes)
print("Counts       : ", counts)

Unique indexes :  [ 10  30  55  77  78  86 109 110 118 181 184 212 234 284 349 369 419 469
 565 588]
Counts       :  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


Look for NaN values in the first colum of Iris dataset

In [72]:
# Set random seed for freezing output
np.random.seed(seed = 42)
# Create duplicate Iris dataset
iris_ds_copy = iris_dataset.copy()
# Check NaN value from the copy of Iris dataset
nanIdx = np.isnan(iris_ds_copy)

#replace Nan with -1 value
iris_ds_copy[nanIdx] = -1

print("Look first twenty items:\n", iris_ds_copy[:20])

Look first twenty items:
 [[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2 -1.   0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4 -1.   0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1 -1. ]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1 -1.  -1.   0.3]]


In [73]:
# Get the first column's values
first_colums_values = iris_ds_copy[:,0]
print("Look first twenty items:\n", first_colums_values[:20].reshape((20, 1)))
# Look for indexes with value that equal -1
idx = np.where(first_colums_values < 0)
print("Indexes of NaN values: ", idx)

Look first twenty items:
 [[5.1]
 [4.9]
 [4.7]
 [4.6]
 [5. ]
 [5.4]
 [4.6]
 [5. ]
 [4.4]
 [4.9]
 [5.4]
 [4.8]
 [4.8]
 [4.3]
 [5.8]
 [5.7]
 [5.4]
 [5.1]
 [5.7]
 [5.1]]
Indexes of NaN values:  (array([ 46,  53,  71, 147]),)


Sorted Iris dataset where 3-column items > 1.5 and 1-coulmn items < 5.0

In [74]:
# Sorted first and third columns from the Iris dataset
sorted_dataset = iris_dataset[np.lexsort((iris_dataset[:, 2], iris_dataset[:, 0]))]
print("Look first twenty items:\n", sorted_dataset[:20])

Look first twenty items:
 [[4.3 3.  1.1 nan]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.6 1.  0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.1 1.5 0.2]
 [4.7 3.2 nan 0.2]
 [4.7 3.2 nan 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 nan 1.4 0.3]
 [4.8 3.4 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]
 [4.9 3.1 1.5 0.1]]


Replace all NaN values with O

In [75]:
# Check NaN index from Iris dataset
nanIdx = np.isnan(iris_dataset)

# Replace Nan with 0 value
iris_dataset[nanIdx] = 0
print("Look first twenty items:\n", iris_dataset[:20])

Look first twenty items:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 0.  0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0. ]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 0.  0.  0.3]]


Count unique values and print their counts


In [85]:
# Get unique values and counts from Iris dataset
unique_values, counts = np.unique(iris_dataset, return_counts=True)
print("Unique items :\n ", unique_values)
print("Counts       :\n ", counts)

Unique items :
  [0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1
 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9
 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7
 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6
 7.7 7.9]
Counts       :
  [ 6 28  7  7  1  1  8  4  7 20 20 26 11  6 12  7  7  6  6 12  6 11  5  9
 14 10 27 12 13  8 12  8  4  4  7  5  6  4  5  3  8  9  7  7  9 11 14 17
  6  3  8 10 12 11 10  5  8  9  4 10  8  5  3 10  3  5  1  1  3  1  1  1
  4  1]


Split Iris dataset into 2 vertical parts

In [77]:
# Split Iris dataset by axis=columns
arr1, arr2 = np.split(iris_dataset, 2, axis=0)
print("Look first half items:\n", arr1.shape)
print("Look second half items:\n",arr2.shape)


Look first half items:
 (75, 4)
Look second half items:
 (75, 4)


Sort by ascending/descending the first columns of arrays

In [78]:
# Ascending array sort by first columns
sorted_arr1 = arr1[arr1[:, 0].argsort()]
# Descending array sort by first columns
sorted_arr2 = arr2[arr2[:, 0].argsort()][::-1]
print("-- First array --- \n")
print(sorted_arr1)
print("\n")
print("-- Second array --- \n")
print(sorted_arr2)

-- First array --- 

[[0.  3.8 1.6 0.2]
 [0.  2.3 4.  1.3]
 [0.  2.8 4.  1.3]
 [4.3 3.  1.1 0. ]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.4 1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.7 3.2 0.  0.2]
 [4.8 0.  1.4 0.3]
 [4.8 3.4 1.9 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.5 1.6 0.6]
 [5.  3.3 1.4 0.2]
 [5.  2.  3.5 1. ]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.5 1.3 0.3]
 [5.  3.4 0.  0.2]
 [5.  3.6 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 0.  0.  0.3]
 [5.1 3.3 1.7 0.5]
 [5.1 3.7 0.  0.4]
 [5.1 3.5 1.4 0.3]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.2 0.  0.  0.2]
 [5.2 2.7 3.9 1.4]
 [5.3 3.7 1.5 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.5 3.5 1.3 0.2]
 [5.5 4.2 

Concatenate both arrays to a to big one

In [79]:
#Concatenate both previous arrays
new_arr = np.concatenate((sorted_arr1, sorted_arr2), axis=0)
print("New array :\n", new_arr)

New array :
 [[0.  3.8 1.6 0.2]
 [0.  2.3 4.  1.3]
 [0.  2.8 4.  1.3]
 [4.3 3.  1.1 0. ]
 [4.4 3.  1.3 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 2.9 1.4 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.4 1.4 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.6 3.2 1.4 0.2]
 [4.7 3.2 0.  0.2]
 [4.7 3.2 0.  0.2]
 [4.8 0.  1.4 0.3]
 [4.8 3.4 1.9 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.8 3.1 1.6 0.2]
 [4.9 3.1 1.5 0.1]
 [4.9 2.4 3.3 1. ]
 [4.9 3.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.5 1.6 0.6]
 [5.  3.3 1.4 0.2]
 [5.  2.  3.5 1. ]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.5 1.3 0.3]
 [5.  3.4 0.  0.2]
 [5.  3.6 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.4 1.5 0.2]
 [5.1 3.5 1.4 0.2]
 [5.1 0.  0.  0.3]
 [5.1 3.3 1.7 0.5]
 [5.1 3.7 0.  0.4]
 [5.1 3.5 1.4 0.3]
 [5.2 4.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [5.2 0.  0.  0.2]
 [5.2 2.7 3.9 1.4]
 [5.3 3.7 1.5 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.4 1.5 0.4]
 [5.4 3.4 1.7 0.2]
 [5.4 3.7 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [5.5 3.5 1.3 0.2]
 [5.5 4.2 1.4 0.2]

Look for the most repeated value in array

In [80]:
# Look for all unique values and their counts
repeat_values, counts = np.unique(new_arr, return_counts=True)
# Get arg max of counts and pass it as index to our array
most_repeat_value = repeat_values[np.argmax(counts)]
print("Most repeated value is: ",most_repeat_value)

Most repeated value is:  0.2


Implementation of math function to work with items

In [81]:
def perform_calculation(array):
    # Calculate the mean of the column
    mean = np.mean(array)

    # Create a mask to identify values less than the mean
    mask = array < mean

    # Multiply values less than the mean by 2
    array[mask] *= 2

    # Divide values greater than or equal to the mean by 4
    array[mask] /= 4

    return array

Apply the perform_calculation func to third column of Iris dataset

In [82]:
# User previous func for calculation task
new_set = perform_calculation(iris_dataset[:, 2])
print("New set: \n",new_set)

New set: 
 [0.7  0.7  0.   0.75 0.7  0.85 0.7  0.   0.7  0.75 0.75 0.8  0.7  0.55
 0.6  0.75 0.65 0.7  0.85 0.   0.85 0.   0.5  0.85 0.95 0.8  0.8  0.
 0.7  0.   0.8  0.75 0.75 0.7  0.75 0.6  0.65 0.75 0.65 0.75 0.65 0.65
 0.65 0.8  0.95 0.7  0.8  0.7  0.75 0.7  4.7  4.5  4.9  4.   4.6  4.5
 4.7  1.65 0.   3.9  1.75 4.2  4.   4.7  1.8  4.4  4.5  4.1  4.5  3.9
 4.8  4.   4.9  4.7  4.3  4.4  4.8  5.   4.5  1.75 3.8  3.7  3.9  5.1
 4.5  4.5  4.7  4.4  4.1  4.   4.4  4.6  4.   1.65 4.2  4.2  4.2  4.3
 1.5  4.1  6.   5.1  5.9  5.6  5.8  6.6  4.5  6.3  5.8  6.1  5.1  5.3
 5.5  5.   5.1  5.3  5.5  6.7  6.9  5.   5.7  4.9  6.7  4.9  5.7  6.
 4.8  4.9  5.6  5.8  6.1  6.4  5.6  5.1  5.6  6.1  5.6  5.5  4.8  5.4
 5.6  5.1  5.1  5.9  5.7  5.2  5.   5.2  5.4  5.1 ]
